name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Prepare
      run: ./gradlew prepareWorkspace

    - name: Build
      run: ./gradlew build

    - name: Generate archive
      uses: actions/upload-artifact@v1
      with:
        name: Results
        path: build/libs/
